# Generated by Django 5.2.18 on 2026-10-10 20:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0007_purchase_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IvaRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tarifa (%)')),
                ('valid_from', models.DateField(verbose_name='Vigente desde')),
                ('legal_reference', models.CharField(max_length=200, verbose_name='Referencia legal')),
            ],
            options={
                'verbose_name': 'Tarifa de IVA',
                'verbose_name_plural': 'Tarifas de IVA',
                'ordering': ('-valid_from',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('price_cents', models.PositiveIntegerField(default=0, verbose_name='Precio anual con IVA (centavos)')),
                ('document_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Documentos por período (vacío = ilimitado)')),
                ('months', models.PositiveSmallIntegerField(default=12, verbose_name='Duración (meses)')),
                ('includes_billing', models.BooleanField(default=True, verbose_name='Incluye facturación y ventas')),
                ('product_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de productos (solo gratuito)')),
                ('provider_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de proveedores (solo gratuito)')),
                ('purchase_limit_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de compras por mes (solo gratuito)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible para contratar')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ('order', 'price_cents'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('method', models.CharField(choices=[('payphone', 'PayPhone'), ('manual', 'Registro manual de la plataforma')], default='payphone', max_length=20, verbose_name='Medio')),
                ('mode', models.CharField(choices=[('inmediato', 'Empieza al confirmar el pago'), ('programado', 'Empieza al terminar el período actual')], default='inmediato', max_length=20, verbose_name='Inicio del período')),
                ('client_tx_id', models.CharField(max_length=50, unique=True, verbose_name='Referencia interna')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='Total (centavos)')),
                ('base_cents', models.PositiveIntegerField(verbose_name='Base imponible (centavos)')),
                ('iva_cents', models.PositiveIntegerField(verbose_name='IVA (centavos)')),
                ('iva_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tarifa de IVA aplicada (%)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('creado', 'Creado'), ('redirigido', 'En PayPhone'), ('aprobado', 'Aprobado'), ('cancelado', 'Cancelado'), ('rechazado', 'Rechazado'), ('expirado', 'Expirado sin confirmar'), ('error_comunicacion', 'Pendiente de conciliación'), ('en_revision', 'En revisión'), ('reversado', 'Reversado')], db_index=True, default='creado', max_length=30, verbose_name='Estado')),
                ('payphone_payment_id', models.CharField(blank=True, max_length=60, verbose_name='Id de preparación PayPhone')),
                ('payphone_transaction_id', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Transacción PayPhone')),
                ('authorization_code', models.CharField(blank=True, max_length=60, verbose_name='Código de autorización')),
                ('card_brand', models.CharField(blank=True, max_length=40, verbose_name='Tarjeta')),
                ('last_digits', models.CharField(blank=True, max_length=4, verbose_name='Últimos dígitos')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Observación')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado')),
                ('redirected_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado a PayPhone')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado')),
                ('invoice_requested', models.BooleanField(default=False, verbose_name='Factura solicitada')),
                ('invoice_data', models.JSONField(blank=True, default=dict, verbose_name='Datos para la factura')),
                ('invoice_number', models.CharField(blank=True, max_length=30, verbose_name='Número de factura emitida')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40, verbose_name='Evento')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Detalle (saneado)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='suscripciones.payment')),
            ],
            options={
                'verbose_name': 'Evento de pago',
                'verbose_name_plural': 'Eventos de pago',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('reemplazada', 'Reemplazada'), ('anulada', 'Anulada')], db_index=True, default='activa', max_length=20, verbose_name='Estado')),
                ('starts_at', models.DateTimeField(verbose_name='Inicio')),
                ('ends_at', models.DateTimeField(verbose_name='Fin')),
                ('document_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Límite de documentos')),
                ('documents_used', models.PositiveIntegerField(default=0, verbose_name='Documentos autorizados')),
                ('documents_reserved', models.PositiveIntegerField(default=0, verbose_name='Documentos en proceso')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Observación')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('replaced_at', models.DateTimeField(blank=True, null=True, verbose_name='Reemplazada el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_periods', to='pos.company', verbose_name='Empresa')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='period', to='suscripciones.payment', verbose_name='Pago')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suscripciones.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Período de suscripción',
                'verbose_name_plural': 'Períodos de suscripción',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='QuotaReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_model', models.CharField(max_length=30, verbose_name='Tipo de comprobante')),
                ('voucher_id', models.PositiveIntegerField(verbose_name='Id del comprobante')),
                ('voucher_label', models.CharField(blank=True, max_length=40, verbose_name='Número')),
                ('status', models.CharField(choices=[('reservada', 'En proceso'), ('consumida', 'Autorizada (consumida)'), ('liberada', 'Liberada')], default='reservada', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pos.company', verbose_name='Empresa')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='suscripciones.subscriptionperiod', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Uso de cupo',
                'verbose_name_plural': 'Usos de cupo',
                'constraints': [models.UniqueConstraint(fields=('company', 'voucher_model', 'voucher_id'), name='cupo_un_registro_por_comprobante')],
            },
        ),
    ]
