# Generated by Django 5.2.18 on 2026-10-09 02:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pos', '0003_multiempresa_esquema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha')),
                ('action', models.CharField(choices=[('login', 'Inicio de sesión'), ('company_switch', 'Cambio de empresa'), ('platform_enter', 'Entrada de la plataforma en una empresa'), ('membership_add', 'Alta de membresía'), ('membership_change', 'Cambio de membresía'), ('membership_remove', 'Baja de membresía'), ('company_create', 'Alta de empresa'), ('company_change', 'Cambio de empresa (datos)')], max_length=40, verbose_name='Acción')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Detalle')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ('-created_at',),
                'default_permissions': ('view',),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de alta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pos.company', verbose_name='Empresa')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='auth.group', verbose_name='Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'permissions': (('view_membership', 'Can view Membresía'), ('add_membership', 'Can add Membresía'), ('change_membership', 'Can change Membresía'), ('delete_membership', 'Can delete Membresía')),
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='membership_user_company_unica')],
            },
        ),
    ]
