# Generated by Django 5.2.18 on 2026-10-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_seguridad_por_filas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('company_switch', 'Cambio de empresa'), ('platform_enter', 'Entrada de la plataforma en una empresa'), ('membership_add', 'Alta de membresía'), ('membership_change', 'Cambio de membresía'), ('membership_remove', 'Baja de membresía'), ('company_create', 'Alta de empresa'), ('company_change', 'Cambio de empresa (datos)'), ('signup', 'Registro de empresa'), ('email_verified', 'Correo confirmado'), ('signup_resend', 'Reenvío del enlace de confirmación')], max_length=40, verbose_name='Acción'),
        ),
    ]
