# Generated by Django 5.2.18 on 2026-10-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_acciones_de_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('company_switch', 'Cambio de empresa'), ('platform_enter', 'Entrada de la plataforma en una empresa'), ('membership_add', 'Alta de membresía'), ('membership_change', 'Cambio de membresía'), ('membership_remove', 'Baja de membresía'), ('company_create', 'Alta de empresa'), ('company_change', 'Cambio de empresa (datos)'), ('signup', 'Registro de empresa'), ('email_verified', 'Correo confirmado'), ('signup_resend', 'Reenvío del enlace de confirmación'), ('plan_payment_start', 'Inicio de pago del plan'), ('plan_manual', 'Activación manual de plan'), ('plan_period_change', 'Cambio de período de suscripción'), ('plan_invoice_request', 'Solicitud de factura de la suscripción')], max_length=40, verbose_name='Acción'),
        ),
    ]
