# Generated by Django 5.2.18 on 2026-10-09 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_empresa_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='creditnotedetail',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='ctascollect',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='debtspay',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='paymentsctacollect',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='paymentsdebtspay',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='promotionsdetail',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='typeexpense',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='vouchererrors',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pos.company', verbose_name='Empresa'),
        ),
    ]
