# Generated by Django 5.2.18 on 2026-10-09 02:25

import core.tenancy.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_multiempresa_obligatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='electronic_signature',
            field=models.FileField(blank=True, null=True, upload_to=core.tenancy.storage.CompanyPath('firma'), verbose_name='Firma electrónica (Archivo P12)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.tenancy.storage.CompanyPath('logo'), verbose_name='Logotipo de la empresa'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_authorized',
            field=models.FileField(blank=True, null=True, upload_to=core.tenancy.storage.CompanyPath('comprobantes/pdf'), verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='xml_authorized',
            field=models.FileField(blank=True, null=True, upload_to=core.tenancy.storage.CompanyPath('comprobantes/xml'), verbose_name='XML Autorizado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to=core.tenancy.storage.CompanyPath('codigos'), verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.tenancy.storage.CompanyPath('productos'), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pdf_authorized',
            field=models.FileField(blank=True, null=True, upload_to=core.tenancy.storage.CompanyPath('comprobantes/pdf'), verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='xml_authorized',
            field=models.FileField(blank=True, null=True, upload_to=core.tenancy.storage.CompanyPath('comprobantes/xml'), verbose_name='XML Autorizado'),
        ),
    ]
